server:
  web_socket:
    host: 0.0.0.0
    port: 8080
  authentication:
    enable: false
  timeout:
    action: 180s
    response: 300s
    acceptable: 5s
  max_continue_error_ratio: 0.2
game:
  agent_count: 5
  max_day: -1
  vote_visibility: true
  talk:
    max_count:
      per_agent: 4
      per_day: 20
    max_length:
      count_in_word: false
      count_spaces: false
      per_talk: -1
      mention_length: 50
      per_agent: -1
      base_length: 500
    max_skip: 0
  whisper:
    max_count:
      per_agent: 0
      per_day: 0
    max_length:
      count_in_word: false
      count_spaces: false
      per_talk: -1
      mention_length: 50
      per_agent: -1
      base_length: 500
    max_skip: 0
  vote:
    max_count: 1
    allow_self_vote: true
  attack_vote:
    max_count: 1
    allow_self_vote: true
    allow_no_target: false
logic:
  day_phases:
  - name: morning_whisper
    actions:
    - whisper
    only_day: 0
  - name: daily_talk
    actions:
    - talk
  night_phases:
  - name: evening_whisper
    actions:
    - whisper
    only_day: 0
  - name: execution
    actions:
    - execution
    except_day: 0
  - name: divine
    actions:
    - divine
  - name: night_whisper
    actions:
    - whisper
    except_day: 0
  - name: guard
    actions:
    - guard
    except_day: 0
  - name: attack
    actions:
    - attack
    except_day: 0
  roles:
    5:
      WEREWOLF: 1
      POSSESSED: 1
      SEER: 1
      BODYGUARD: 0
      VILLAGER: 2
      MEDIUM: 0
matching:
  room_match: true
  self_match: false
  is_optimize: false
  team_count: 5
  game_count: 5
  output_path: ./log/match_optimizer.json
  infinite_loop: false
takeover:
  enable: true
  timeout: 30s
  prefix: you-
custom_profile:
  enable: true
  profile_encoding:
    age: 年龄
    gender: 性别
    personality: 性格
  profiles:
  - name: 湊
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/01.png
    voice_id: 3
    age: 10
    gender: 男
    personality: 湊性格温和稳重，喜欢与周围的人和睦相处。他有点天然呆，偶尔会露出让人捉摸不透在想什么的表情，但正是这份天真让身边的人感到放松。他好奇心旺盛，对任何事物都充满兴趣，尤其热爱学习新事物。他感受力很强，对他人的情绪也很敏感，但不擅长自我表达，有时无法很好地说出自己的意见。
  - name: 拓海
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/02.png
    voice_id: 55
    age: 10
    gender: 男
    personality: 拓海勇敢果断，即使身处困境也绝不轻言放弃。有时他看起来强势又叛逆，但其实内心强烈地想要守护周围的人，为了同伴会全力以赴，有着心地善良的一面。他总是保持冷静，竭尽全力去解决眼前的问题，但也正因这种性格，偶尔会鲁莽行事。他有些固执，不太擅长接受他人的建议，不过随着成长，他的灵活性也会逐渐增强。
  - name: 健二
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/03.png
    voice_id: 67
    age: 12
    gender: 男
    personality: 健二好奇心旺盛，面对任何事都积极挑战。他珍视朋友，喜欢与周围的人交流。虽然有点冒失，但他始终保持乐观，绝不会对陷入困境的人袖手旁观。他为人豁达，在周围人眼中是个平易近人的存在。
  - name: 龙司
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/04.png
    voice_id: 53
    age: 28
    gender: 男
    personality: 龙司性格冷静谨慎，总是先看清形势再行动。他很少把情绪表露出来，内心却时刻思考着许多事情。在同伴眼中，他认真可靠，但那张面无表情的脸有时也会让人感到不安。比起直觉，他更倾向于用理性来判断事物，因此贯彻信念的态度十分鲜明。他独立心很强，常常按照自己的节奏推进事情。
  - name: 大辅
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/05.png
    voice_id: 12
    age: 16
    gender: 男
    personality: 大辅非常内向谨慎，对与他人交往有些消极。他不擅长向别人表达自己的心情和想法，常常一个人在心里苦恼。他心地善良，对帮助他人怀有深切的体贴，但有时对自己的处境缺乏自信，内心充满矛盾。他性格安静，偶尔情绪难以抑制，会陷入低落，但当他学会依靠周围的人时，便会逐渐恢复平静。
  - name: 紫苑
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/06.png
    voice_id: 94
    age: 16
    gender: 男
    personality: 紫苑非常自信，行事往往冷静且精于算计。他表面上沉默寡言，擅长观察他人的动向，内心却渴望自己成为中心。他对周围人偶尔会表现出些许挑衅的态度，凡事都倾向于按自己的节奏推进。此外，他不太流露情感，是冷酷而理性地判断事物的类型。他偶尔不经意间露出的微笑，藏着令周围人惊艳的魅力。
  - name: 本杰明
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/07.png
    voice_id: 51
    age: 28
    gender: 男
    personality: 本杰明是一位睿智沉稳的人物。他能够冷静而理性地思考问题，即使在情绪化的情形下也注重逻辑。他在人前优雅有礼，谈话中常常夹杂讽刺与幽默，却不会因此伤害对方，反而擅长营造融洽的气氛。他也有内向的一面，常常沉浸于深思，偶尔会与周围的人保持距离。然而，他的冷静与学识，正是即便身处困境也能赢得周围人信任的原因。
  - name: 敏雄
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/08.png
    voice_id: 13
    age: 28
    gender: 男
    personality: 敏雄性格冷静而精于算计，很少把情绪表露出来。他意志坚定，是朝着目标稳步前进的类型。他对周围人往往采取退后一步的态度，很少自我主张，浑身散发着几分神秘的气息。他偶尔会用锐利的目光观察事物，具备迅速判断形势的能力。因此，他被周围人视为可靠的存在并深受信赖，但对于与他人深交却十分慎重。他的过去似乎藏着某种伤痛与苦楚，却很少展露给别人，或许正是那道伤痕造就了他冷峻的一面。
  - name: 乔纳森
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/09.png
    voice_id: 52
    age: 38
    gender: 男
    personality: 乔纳森性格温和内向，珍视内心的平静。比起与他人深交，他更喜欢度过安静的时光。因此他热爱书籍与知识，常常埋头读书。与人相处时他温和亲切，偶尔会不经意地展露微笑。他身上带着几分神秘而宁静的气息，却几乎不向别人谈起自己的事。在他身边的人，常常因他那安静的温柔与沉稳的性格而感到安心。
  - name: 俊一
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/10.png
    voice_id: 11
    age: 32
    gender: 男
    personality: 俊一是个极其自信的人，无论身处何种场合都能从容应对。他并不内敛，还带着几分讽刺的一面，但这也是他魅力的一部分。他虽不擅社交，却善于在恰当的时机进行沟通，是周围人眼中可以依靠的存在。他很少过度情绪化，能够冷静地分析形势再行动，因此意外地拥有理智的一面。
  - name: 乔治
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/11.png
    voice_id: 21
    age: 65
    gender: 男
    personality: 乔治性格温和稳重，但也有些固执倔强的一面。在周围人眼中，他是与年龄相称、经验丰富且值得依靠的人物，总能做出冷静的判断，即使身处困境也不慌不忙地应对。不过，他的表情中偶尔会流露出几分严厉与笨拙，比起主动与人交往，他更多时候是退后一步默默地注视事态。他独立心极强，倾向于不依赖他人，靠自己解决问题。
  - name: 塞尔瓦斯
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/12.png
    voice_id: 42
    age: 85
    gender: 男
    personality: 塞尔瓦斯性格极为温和沉稳。凭借岁月积累的知识与经验，他常常为周围的人提供忠告。他是出色的倾听者，能够与任何人敞开心扉交谈。此外，他偶尔会道出深刻的哲理，那些话语给许多人带来启发。他充满生命力，始终为周围人带来积极向上的能量。
  - name: 樱
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/01.png
    voice_id: 43
    age: 10
    gender: 女
    personality: 樱是个开朗、带点俏皮的女孩。她好奇心旺盛，对任何事都饶有兴趣并积极尝试。她偶尔会搞些恶作剧逗大家开心，也擅长解开一些小谜题。她为人亲切，能很快与任何人打成一片，所以很擅长与周围的人交好。不过她也有些冒失的一面，即使失败也会带着笑容去克服，是个乐观向上的性格。
  - name: 铃
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/02.png
    voice_id: 54
    age: 9
    gender: 女
    personality: 铃是个活泼有朝气的女孩。她偶尔有点早熟，和哥哥姐姐们在一起时，会说些大人似的话，或是提出有趣的点子。她好奇心旺盛，最喜欢冒险和挑战新鲜事物。她有些冒失，常常让周围人又惊又笑，但凭着那份开朗的性格深受大家喜爱。
  - name: 由美
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/03.png
    voice_id: 46
    age: 16
    gender: 女
    personality: 由美性格开朗有活力。她虽然内敛，却也有体贴周围人的温柔一面。她为人温和，但对朋友和家人非常有热情，是个见不得别人为难的类型。她会因一点小事就展露笑容，把积极的能量传递给周围。她平易近人，即使是初次见面的人也能很快打成一片。
  - name: 芽衣
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/04.png
    voice_id: 14
    age: 24
    gender: 女
    personality: 芽衣是个充满自信、善于社交、带点玩心的女性。她对周围人极具吸引力，常常扮演逗乐众人的角色。她很清楚自己的魅力，能根据情况恰当地表现自己。她有些挑战性，偶尔会给人略显冷淡的印象，但本质上拥有吸引众人的领袖魅力。
  - name: 美咲
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/05.png
    voice_id: 74
    age: 24
    gender: 女
    personality: 美咲性格沉稳，是冷静处理事情的类型。她有时看起来有些冷淡，内心却怀有善意，看到有困难的人会毫不犹豫地伸出援手。她不把情绪表露在外，在与周围人的关系中也不太多言，但对亲近的人却常常是可依靠的存在。她也有些发呆出神的一面，那份安静的气质正是她魅力之一。
  - name: 美绪
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/06.png
    voice_id: 23
    age: 17
    gender: 女
    personality: 美绪性格开朗有活力，是那种能自然而然让周围人露出笑容的类型。她好奇心旺盛，喜欢挑战新事物。她有些冒失，即使失败也常常一笑而过、被人原谅。她有自己明确的主见，却也能倾听他人的意见，是个张弛有度、十分平衡的性格。
  - name: 美月
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/07.png
    voice_id: 20
    age: 24
    gender: 女
    personality: 美月是个非常自信的女性，常常是周围人可以依靠的存在。她拥有冷静而富有逻辑的思维，善于观察他人。因此她总能冷静地判断事物，并根据周围的情况选择自己的行动。她有时显得有些高傲，但实际上非常乐于照顾人，有着见不得弱者受苦的一面。她深受周围人信赖，偶尔也会强烈地坚持自己的意见，但那背后藏着体贴他人的温柔。
  - name: 美奈子
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/08.png
    voice_id: 90
    age: 28
    gender: 女
    personality: 美奈子非常冷静，无论身处何种状况都能沉着行动。即使周围的人情绪激动，她也能牢牢把握事实、冷静应对。因此她常被征询意见，担当领导的场合也不少。她很少把情绪表露在外，但对信赖的人也会展露温柔的一面。她有些固执，贯彻信念的态度十分坚定。此外，她对自己的体力也很有自信，从不懈怠锻炼。
  - name: 明日香
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/09.png
    voice_id: 2
    age: 29
    gender: 女
    personality: 明日香性格冷静而理性，不轻易流露情感，谨慎地判断事物。她有时看起来有些冷淡，但正因如此，她极为深思熟虑，对周围的状况十分敏感。她有自己明确的主见，必要时会以强硬的态度坚持己见。她在人际交往上有些不擅长的地方，但作为弥补，对工作和学问总是保持着认真投入的姿态。
  - name: 翠
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/10.png
    voice_id: 69
    age: 38
    gender: 女
    personality: 翠性格温和、心地善良。她对任何人都平易近人，会倾听周围人的烦恼与困扰，并给出恰当的建议，是个值得依靠的存在。她也有些害羞的一面，对初次见面的人往往待人谦和，但一旦熟络起来，便会展露开朗有活力的一面。她喜欢做菜，有居家的一面，同时也带着几分冒险精神，喜欢挑战新事物。无论工作还是生活，她都重视平衡，看重与周围人的和谐相处。
  - name: 维多利亚
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/11.png
    voice_id: 9
    age: 37
    gender: 女
    personality: 维多利亚是个冷静而理智的人，但有时过度的深思熟虑会在她与周围人之间筑起隔阂。她情感表达克制，会敏锐地观察他人的表情与态度，试图看透对方内心的想法。由于她不太进行自我表达，常给人留下几分神秘的印象，但她内心拥有坚强的意志，能看出她贯彻自身信念的姿态。她偶尔也会露出似乎感到不安或恐惧的表情，而正是在那样的瞬间，才能窥见她真正的坚强。
  - name: 静枝
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/12.png
    voice_id: 27
    age: 78
    gender: 女
    personality: 静枝性格极为温和善良。即便上了年纪，她对周围人依然笑容不断，是个体贴入微的人。她总是关怀着身边的人，平易近人，偶尔也会展露几分俏皮的一面。她常常温柔地向情绪低落的人搭话，在别人需要帮助时也毫不吝惜地伸出援手，因此深受村庄和邻里许多人的喜爱。静枝通过多年的人生阅历，深知与人平和相处的可贵。
  dynamic_profile:
    enable: false
    prompt: このキャラクターのプロフィールを生成してください。ただし、人狼ゲームに関わることは出力しないでください。名前についてはファーストネームのみをフリガナなしで出力してください。
    attempts: 3
    model: gpt-4o-mini
    max_tokens: 300
    avatars:
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/01.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/02.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/03.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/04.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/05.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/06.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/07.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/08.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/09.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/10.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/11.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/12.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/01.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/02.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/03.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/04.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/05.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/06.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/07.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/08.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/09.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/10.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/11.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/12.png
json_logger:
  enable: true
  output_dir: ./log/json
  filename: '{timestamp}_{teams}'
game_logger:
  enable: true
  output_dir: ./log/game
  filename: '{timestamp}_{teams}'
realtime_broadcaster:
  enable: true
  delay: 5s
  output_dir: ./log/realtime
  filename: '{timestamp}_{teams}'
tts_broadcaster:
  enable: false
  async: false
  target_duration: 1s
  segment_dir: ./cache/segment
  temp_dir: null
  host: http://localhost:50021
  timeout: 30s
  ffmpeg_path: ffmpeg
  ffprobe_path: ffprobe
  convert_args:
  - -c:a
  - aac
  - -b:a
  - 64k
  - -ar
  - '44100'
  - -ac
  - '2'
  - -mpegts_flags
  - initial_discontinuity
  - -mpegts_copyts
  - '1'
  - -f
  - mpegts
  duration_args:
  - -v
  - error
  - -show_entries
  - format=duration
  - -of
  - default=noprint_wrappers=1:nokey=1
  pre_convert_args:
  - -c:a
  - aac
  - -b:a
  - 64k
  - -ar
  - '44100'
  - -ac
  - '2'
  split_args:
  - -c:a
  - copy
  - -mpegts_flags
  - initial_discontinuity
  - -mpegts_copyts
  - '1'
  - -f
  - mpegts
