server:
  web_socket:
    host: 0.0.0.0
    port: 8080
  authentication:
    enable: false
  timeout:
    action: 180s
    response: 300s
    acceptable: 5s
  max_continue_error_ratio: 0.2
game:
  agent_count: 5
  max_day: -1
  vote_visibility: true
  talk:
    max_count:
      per_agent: 4
      per_day: 20
    max_length:
      count_in_word: false
      count_spaces: false
      per_talk: -1
      mention_length: 50
      per_agent: -1
      base_length: 500
    max_skip: 0
  whisper:
    max_count:
      per_agent: 0
      per_day: 0
    max_length:
      count_in_word: false
      count_spaces: false
      per_talk: -1
      mention_length: 50
      per_agent: -1
      base_length: 500
    max_skip: 0
  vote:
    max_count: 1
    allow_self_vote: true
  attack_vote:
    max_count: 1
    allow_self_vote: true
    allow_no_target: false
logic:
  day_phases:
  - name: morning_whisper
    actions:
    - whisper
    only_day: 0
  - name: daily_talk
    actions:
    - talk
  night_phases:
  - name: evening_whisper
    actions:
    - whisper
    only_day: 0
  - name: execution
    actions:
    - execution
    except_day: 0
  - name: divine
    actions:
    - divine
  - name: night_whisper
    actions:
    - whisper
    except_day: 0
  - name: guard
    actions:
    - guard
    except_day: 0
  - name: attack
    actions:
    - attack
    except_day: 0
  roles:
    5:
      WEREWOLF: 1
      POSSESSED: 1
      SEER: 1
      BODYGUARD: 0
      VILLAGER: 2
      MEDIUM: 0
matching:
  room_match: true
  self_match: false
  is_optimize: false
  team_count: 5
  game_count: 5
  output_path: ./log/match_optimizer.json
  infinite_loop: false
takeover:
  enable: true
  timeout: 30s
  prefix: you-
custom_profile:
  enable: true
  profile_encoding:
    age: العمر
    gender: الجنس
    personality: الشخصية
  profiles:
  - name: ميناتو
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/01.png
    voice_id: 3
    age: 10
    gender: ذكر
    personality: ميناتو شخصية هادئة الطباع، يفضّل التعامل مع من حوله بلطف وسكينة.
      فيه شيء من البراءة، وأحيانًا يرتسم على وجهه تعبير يصعب معه معرفة ما يفكّر فيه،
      لكن هذه العفوية تبعث الراحة في نفوس من حوله. يتميّز بفضول كبير، ويبدي اهتمامًا
      بكل شيء، وخاصةً يعشق تعلّم الأشياء الجديدة. شديد الحساسية ومرهف المشاعر تجاه
      الآخرين، لكنه يجد صعوبة في فرض رأيه، وأحيانًا لا يقدر على التعبير عن رأيه بوضوح.
  - name: تاكومي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/02.png
    voice_id: 55
    age: 10
    gender: ذكر
    personality: تاكومي شجاع لا يستسلم أبدًا حتى في أصعب المواقف. قد يبدو أحيانًا
      متمرّدًا وحادّ الطبع، لكنه في الحقيقة يحمل رغبة قوية في حماية من حوله، وفيه
      جانب رقيق يبذل من أجله كل ما في وسعه لأجل رفاقه. يبقى دائمًا رابط الجأش ويفكّر
      مليًّا لحلّ المشكلة التي أمامه، لكن طبعه هذا قد يدفعه أحيانًا إلى التصرّف باندفاع.
      هو عنيد قليلًا ويجد صعوبة في تقبّل نصائح الآخرين، لكنه سيكتسب مرونة أكبر مع
      نموّه ونضجه.
  - name: كينجي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/03.png
    voice_id: 67
    age: 12
    gender: ذكر
    personality: كينجي فضولي بطبعه ويحبّ خوض التحدّيات بحماس. يعتزّ بأصدقائه ويميل
      إلى التواصل مع من حوله. فيه شيء من الطيش أحيانًا، لكنه دائم الإيجابية ولا يتخلّى
      أبدًا عمّن هو في ضيق. هو سمح الطباع، ويراه من حوله شخصًا سهل المعشر ودودًا.
  - name: ريوجي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/04.png
    voice_id: 53
    age: 28
    gender: ذكر
    personality: ريوجي شخصية هادئة وحذرة، يتصرّف دائمًا بعد تمحيص الموقف. نادرًا ما
      يُظهر مشاعره، وفي داخله يفكّر في أمور كثيرة. يثق به رفاقه ويرونه جادًّا يُعتمد
      عليه، إلا أنّ ملامحه الجامدة قد تبعث القلق أحيانًا. لأنه يحكم على الأمور بالعقل
      أكثر من الحدس، يظهر فيه بوضوح تمسّكه بمبادئه. يتمتّع بروح استقلالية عالية، وكثيرًا
      ما يمضي في أموره على وتيرته الخاصة.
  - name: دايسكي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/05.png
    voice_id: 12
    age: 16
    gender: ذكر
    personality: دايسكي شخصية شديدة الانطواء والحذر، وفيه شيء من التحفّظ تجاه التعامل
      مع الآخرين. يجد صعوبة في التعبير عن مشاعره وأفكاره للآخرين، وكثيرًا ما يحبس
      همومه في داخله. يحمل في قلبه طيبة، وهو شديد العطف في مساعدة الآخرين، لكنه أحيانًا
      يفتقد الثقة بمكانته ويصارع نفسه في داخله. هو هادئ الطبع، وقد تطغى عليه مشاعره
      أحيانًا فيهبط مزاجه، لكنه يستعيد سكينته تدريجيًّا حين يتعلّم أن يتّكئ على من
      حوله.
  - name: شيون
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/06.png
    voice_id: 94
    age: 16
    gender: ذكر
    personality: شيون واثق من نفسه إلى حدّ بعيد، وكثيرًا ما يتصرّف بهدوء وحساب دقيق.
      يبدو في الظاهر هادئًا بارعًا في مراقبة تحرّكات الآخرين، لكنه في داخله يرغب في
      أن يكون مركز الأحداث. يُظهر أحيانًا موقفًا فيه شيء من التحدّي تجاه من حوله،
      ويميل إلى إدارة كل أمر على وتيرته الخاصة. إضافةً إلى ذلك، نادرًا ما يُظهر مشاعره،
      وهو من النوع الذي يحكم على الأمور بمنطق بارد. وفي ابتسامته المفاجئة التي تبدو
      منه أحيانًا سحر يبهر من حوله.
  - name: بنجامين
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/07.png
    voice_id: 51
    age: 28
    gender: ذكر
    personality: بنجامين شخصية مثقّفة هادئة الطباع. يقدر على التفكير في الأمور بهدوء
      وعقلانية، ويغلّب المنطق حتى في المواقف العاطفية. أنيق ومهذّب أمام الناس، وكثيرًا
      ما يطعّم حديثه بالسخرية والفكاهة، لكنه بارع في صنع جوّ ودّي دون أن يجرح محدّثه.
      فيه جانب انطوائي أيضًا، وكثيرًا ما يغرق في تأمّل عميق، وقد ينأى بنفسه أحيانًا
      عمّن حوله. غير أنّ هدوءه ومعرفته يجعلانه موضع ثقة من حوله حتى في أصعب المواقف.
  - name: توشيو
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/08.png
    voice_id: 13
    age: 28
    gender: ذكر
    personality: توشيو شخصية هادئة محسوبة الخطى، نادرًا ما يُظهر مشاعره. يملك إرادة
      قوية، وهو من النوع الذي يتقدّم بثبات نحو هدفه. يميل إلى الوقوف على مسافة من
      الآخرين، قليل فرض الرأي، وتحيط به هالة من الغموض. أحيانًا يراقب الأمور بنظرة
      ثاقبة وله قدرة على تقييم الموقف بسرعة. لذلك يثق به من حوله بوصفه شخصًا يُعتمد
      عليه، لكنه حذر في الانخراط العميق مع الآخرين. يبدو أنّ في ماضيه ألمًا أو معاناة
      من نوع ما، إلا أنه قلّما يُظهر ذلك لأحد، وربما يكون أثر تلك الجراح هو ما يرتبط
      بجانبه البارد.
  - name: جوناثان
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/09.png
    voice_id: 52
    age: 38
    gender: ذكر
    personality: جوناثان شخصية وادعة وانطوائية، يحرص على سكينة قلبه. يفضّل قضاء أوقات
      هادئة على الانخراط العميق مع الآخرين. لذلك يعشق الكتب والمعرفة، وكثيرًا ما تراه
      منهمكًا في القراءة. لطيف ودود حين يتعامل مع الناس، وتبدو منه ابتسامة عابرة بين
      الحين والآخر. تحيط به أجواء غامضة وادعة، ومع ذلك نادرًا ما يحدّث الآخرين عن
      نفسه. وكثيرًا ما يشعر من حوله بالطمأنينة من لطفه الهادئ وطباعه الساكنة.
  - name: شونإتشي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/10.png
    voice_id: 11
    age: 32
    gender: ذكر
    personality: شونإتشي شخصية مفعمة بالثقة، من النوع القادر على الاحتفاظ برباطة جأشه
      في أيّ موقف. ليس متحفّظًا، وفيه جانب فيه شيء من السخرية، لكن ذلك جزء من سحره.
      ليس اجتماعيًّا كثيرًا، لكنه بارع في التواصل في اللحظة المناسبة، ويراه من حوله
      شخصًا يُعتمد عليه. قلّما ينفعل عاطفيًّا بإفراط، ويقدر على تحليل الموقف بهدوء
      والتصرّف بناءً عليه، فيظهر فيه جانب عقلاني قد يفاجئ من حوله.
  - name: جورج
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/11.png
    voice_id: 21
    age: 65
    gender: ذكر
    personality: جورج شخصية وادعة هادئة، لكن فيه شيئًا من العناد والإصرار. يراه من
      حوله شخصًا واسع الخبرة بما يليق بسنّه، يُعتمد عليه، إذ يقدر دائمًا على اتخاذ
      قرارات حكيمة، فيتعامل مع أصعب المواقف دون اضطراب. ومع ذلك، قد تترشّح من ملامحه
      أحيانًا قسوة أو شيء من الفظاظة، وهو يميل إلى مراقبة الأمور من مسافة بدلًا من
      الانخراط الفعّال مع الآخرين. يتمتّع بروح استقلالية عالية، ويميل إلى حلّ مشكلاته
      بنفسه دون الاتكاء على أحد.
  - name: سيرفاس
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/12.png
    voice_id: 42
    age: 85
    gender: ذكر
    personality: سيرفاس شخصية وادعة هادئة إلى حدّ بعيد. وبناءً على ما اكتسبه من معرفة
      وخبرة مع تقدّم السنّ، كثيرًا ما يسدي النصح لمن حوله. هو مستمع بارع، ويقدر على
      محادثة الجميع بقلب مفتوح. كما أنه يطرح أحيانًا أفكارًا فلسفية عميقة تلهم كثيرًا
      من الناس. مفعم بطاقة الحياة، وحضوره يبثّ في من حوله طاقة إيجابية دائمة.
  - name: ساكورا
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/01.png
    voice_id: 43
    age: 10
    gender: أنثى
    personality: ساكورا فتاة مرحة فيها شيء من الشقاوة. فضولية بطبعها، تبدي اهتمامًا
      بكل شيء وتخوض التحدّيات بحماس. بارعة أحيانًا في إضحاك من حولها بمزحة بسيطة أو
      في حلّ لغز صغير. ودودة تألف الجميع بسرعة، فتجيد عقد الصداقات مع من حولها. لكن
      فيها جانبًا طائشًا قليلًا، وهي شخصية إيجابية تحاول تجاوز إخفاقاتها بابتسامة.
  - name: رين
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/02.png
    voice_id: 54
    age: 9
    gender: أنثى
    personality: رين فتاة نشيطة مفعمة بالحيوية. أحيانًا فيها شيء من النضج المبكر،
      فحين تكون برفقة من هم أكبر سنًّا تتحدّث بكلام الكبار أو تطرح أفكارًا طريفة.
      فضولية بطبعها، تعشق المغامرة وخوض الأشياء الجديدة. فيها جانب طائش قليلًا، وكثيرًا
      ما تفاجئ من حولها أو تُضحكهم، لكنها محبوبة من الجميع بطباعها المرحة.
  - name: يومي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/03.png
    voice_id: 46
    age: 16
    gender: أنثى
    personality: يومي شخصية مرحة مفعمة بالحيوية. متحفّظة، ومع ذلك فيها جانب لطيف يهتمّ
      بمن حولها. هادئة الطباع، لكنها شديدة الحماس تجاه أصدقائها وعائلتها، ومن النوع
      الذي لا يقدر على ترك من هو في ضيق. تبتسم لأبسط الأمور، وحضورها ينشر طاقة إيجابية
      في من حولها. ودودة تألف حتى من تلتقيه لأول مرة بسرعة.
  - name: مي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/04.png
    voice_id: 14
    age: 24
    gender: أنثى
    personality: مي امرأة واثقة من نفسها، اجتماعية، فيها روح مرحة. حضورها جذّاب لمن
      حولها، وكثيرًا ما تؤدّي دور من يُدخل البهجة على الآخرين. تعرف سحرها جيّدًا،
      وتقدر على التصرّف باللياقة المناسبة وفق الموقف. فيها شيء من التحدّي، وقد تعطي
      أحيانًا انطباعًا فيه شيء من البرود، لكنها في الأساس تملك كاريزما تأسر الناس.
  - name: ميساكي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/05.png
    voice_id: 74
    age: 24
    gender: أنثى
    personality: ميساكي شخصية هادئة، تتعامل مع الأمور برباطة جأش. قد تبدو فظّة قليلًا،
      لكنها تحمل في داخلها لطفًا، فلا تتردّد في مدّ يد العون حين ترى من هو في ضيق.
      لا تُظهر مشاعرها، ولا تكثر الكلام في علاقاتها مع من حولها، لكنها كثيرًا ما تكون
      موضع اعتماد ممّن يقربون منها. فيها شيء من الشرود، وفي أجوائها الساكنة سحر من
      سحرها.
  - name: ميو
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/06.png
    voice_id: 23
    age: 17
    gender: أنثى
    personality: ميو شخصية مرحة مفعمة بالحيوية، من النوع الذي يرسم البسمة على وجوه
      من حوله بعفوية. فضولية بطبعها، تحبّ خوض الأشياء الجديدة. فيها جانب طائش قليلًا،
      وكثيرًا ما يُغتفر لها خطؤها بابتسامة. تحمل رأيًا واضحًا خاصًّا بها، لكنها قادرة
      أيضًا على الإصغاء لآراء الآخرين، فهي شخصية متّزنة.
  - name: ميزوكي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/07.png
    voice_id: 20
    age: 24
    gender: أنثى
    personality: ميزوكي امرأة مفعمة بالثقة، كثيرًا ما تكون موضع اعتماد من حولها. تتمتّع
      بتفكير هادئ منطقي، وقادرة على مراقبة الناس عن كثب. لذلك تحكم على الأمور دائمًا
      بهدوء، وتختار تصرّفاتها وفق الموقف من حولها. قد تبدو أحيانًا متعالية قليلًا،
      لكنها في الحقيقة شديدة الاهتمام بالآخرين، وفيها جانب لا يقدر على ترك الضعفاء
      وحدهم. يُعتمد عليها من حولها، وقد تتمسّك أحيانًا برأيها بقوة، لكن خلف ذلك لطفًا
      يراعي الآخرين.
  - name: ميناكو
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/08.png
    voice_id: 90
    age: 28
    gender: أنثى
    personality: ميناكو شخصية هادئة إلى حدّ بعيد، تتصرّف برباطة جأش في أيّ موقف. حتى
      حين ينفعل من حولها عاطفيًّا، تتمسّك بالحقائق وتتعامل بهدوء. لذلك كثيرًا ما يُطلب
      رأيها، وليست المواقف التي تتولّى فيها زمام القيادة بقليلة. نادرًا ما تُظهر مشاعرها،
      لكنها تُظهر لطفها لمن تثق بهم. فيها شيء من العناد، وتمسّكها بمبادئها قويّ. كما
      أنها واثقة من لياقتها البدنية ولا تفرّط في التدريب.
  - name: أسكا
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/09.png
    voice_id: 2
    age: 29
    gender: أنثى
    personality: أسكا شخصية هادئة منطقية، لا تُظهر مشاعرها وتحكم على الأمور بحذر.
      قد تبدو فظّة قليلًا، لكنها في المقابل شديدة التروّي وحسّاسة لما يدور حولها.
      تحمل رأيًا واضحًا خاصًّا بها، وتتمسّك به بحزم عند الحاجة. تجد بعض الصعوبة في
      العلاقات الاجتماعية، لكنها في المقابل لا تتخلّى عن جدّيتها في العمل والدراسة.
  - name: ميدوري
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/10.png
    voice_id: 69
    age: 38
    gender: أنثى
    personality: السيّدة ميدوري شخصية وادعة طيّبة القلب. ودودة مع الجميع، تصغي إلى
      هموم من حولها ومشكلاتهم وتسدي لهم النصح الصائب، فهي شخص يُعتمد عليه. فيها جانب
      خجول قليلًا، وكثيرًا ما تتعامل بتحفّظ مع من تلتقيه لأول مرة، لكنها تُظهر جانبًا
      مرحًا مفعمًا بالحيوية بعد أن تألفه. تحبّ الطبخ، وفيها جانب بيتيّ، لكن فيها أيضًا
      روح مغامرة، فهي تحبّ خوض الأشياء الجديدة. تحرص على التوازن في العمل وفي حياتها
      الخاصة، وتولي أهمّيةً للوئام مع من حولها.
  - name: فيكتوريا
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/11.png
    voice_id: 9
    age: 37
    gender: أنثى
    personality: فيكتوريا شخصية هادئة عاقلة، لكن فرط تروّيها يبني أحيانًا جدارًا بينها
      وبين من حولها. تعبيرها عن مشاعرها متحفّظ، وتراقب ملامح الآخرين ومواقفهم بحدّة،
      محاولةً استشفاف ما يدور في خواطرهم. لأنها قليلة التعبير عن نفسها، كثيرًا ما
      تعطي للآخرين انطباعًا غامضًا، لكنها في داخلها تملك إرادة قوية، ويبدو منها موقف
      متمسّك بمبادئها. تبدو منها أحيانًا ملامح قلق أو خوف، لكن في تلك اللحظات بالذات
      تلوح قوّتها الحقيقية.
  - name: شيزوي
    avatar_url: https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/12.png
    voice_id: 27
    age: 78
    gender: أنثى
    personality: شيزوي شخصية وادعة لطيفة إلى حدّ بعيد. ورغم تقدّمها في السنّ، لا تفارق
      وجهها ابتسامة دافئة لمن حولها، فهي إنسانة شديدة العطف. تهتمّ دائمًا بمن حولها،
      ودودة، وتُظهر أحيانًا جانبًا فيه شيء من المرح. تواسي من فقد عزيمته بكلمة لطيفة،
      ولا تبخل بمدّ يد العون لمن يحتاج، لذلك يحبّها كثيرون في القرية والمنطقة. لقد
      أدركت شيزوي، عبر تجارب سنواتها الطويلة، قيمة العيش بسلام مع الناس.
  dynamic_profile:
    enable: false
    prompt: このキャラクターのプロフィールを生成してください。ただし、人狼ゲームに関わることは出力しないでください。名前についてはファーストネームのみをフリガナなしで出力してください。
    attempts: 3
    model: gpt-4o-mini
    max_tokens: 300
    avatars:
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/01.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/02.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/03.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/04.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/05.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/06.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/07.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/08.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/09.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/10.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/11.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/male/12.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/01.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/02.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/03.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/04.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/05.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/06.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/07.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/08.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/09.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/10.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/11.png
    - https://aiwolfdial.github.io/aiwolf-nlp-viewer/images/female/12.png
json_logger:
  enable: true
  output_dir: ./log/json
  filename: '{timestamp}_{teams}'
game_logger:
  enable: true
  output_dir: ./log/game
  filename: '{timestamp}_{teams}'
realtime_broadcaster:
  enable: true
  delay: 5s
  output_dir: ./log/realtime
  filename: '{timestamp}_{teams}'
tts_broadcaster:
  enable: false
  async: false
  target_duration: 1s
  segment_dir: ./cache/segment
  temp_dir: null
  host: http://localhost:50021
  timeout: 30s
  ffmpeg_path: ffmpeg
  ffprobe_path: ffprobe
  convert_args:
  - -c:a
  - aac
  - -b:a
  - 64k
  - -ar
  - '44100'
  - -ac
  - '2'
  - -mpegts_flags
  - initial_discontinuity
  - -mpegts_copyts
  - '1'
  - -f
  - mpegts
  duration_args:
  - -v
  - error
  - -show_entries
  - format=duration
  - -of
  - default=noprint_wrappers=1:nokey=1
  pre_convert_args:
  - -c:a
  - aac
  - -b:a
  - 64k
  - -ar
  - '44100'
  - -ac
  - '2'
  split_args:
  - -c:a
  - copy
  - -mpegts_flags
  - initial_discontinuity
  - -mpegts_copyts
  - '1'
  - -f
  - mpegts
